<?php

// autoload_static.php @generated by Composer

namespace Composer\Autoload;

class ComposerStaticInitb52900ff297b269f1bdb8c9991a494a7
{
    public static $prefixLengthsPsr4 = array (
        'J' => 
        array (
            'Jordi\\BlueskyPhp\\' => 17,
        ),
    );

    public static $prefixDirsPsr4 = array (
        'Jordi\\BlueskyPhp\\' => 
        array (
            0 => __DIR__ . '/../..' . '/src',
        ),
    );

    public static $classMap = array (
        'Composer\\InstalledVersions' => __DIR__ . '/..' . '/composer/InstalledVersions.php',
    );

    public static function getInitializer(ClassLoader $loader)
    {
        return \Closure::bind(function () use ($loader) {
            $loader->prefixLengthsPsr4 = ComposerStaticInitb52900ff297b269f1bdb8c9991a494a7::$prefixLengthsPsr4;
            $loader->prefixDirsPsr4 = ComposerStaticInitb52900ff297b269f1bdb8c9991a494a7::$prefixDirsPsr4;
            $loader->classMap = ComposerStaticInitb52900ff297b269f1bdb8c9991a494a7::$classMap;

        }, null, ClassLoader::class);
    }
}
